[Config]
MinimumVersion=27~devel
Profiles=
		bootc

[Build]
ToolsTree=default
History=yes
CacheDirectory=mkosi.cache
Incremental=yes

[Distribution]
Distribution=arch
Release=rolling
Repositories=core
			extra
			multilib
			core-testing

[Output]
ImageId=meownix
OutputDirectory=mkosi.output
Output=%i_%v_%a

