[Config]
MinimumVersion=27~devel
Profiles=
		bootc

[Build]
ToolsTree=default
History=yes
CacheDirectory=mkosi.cache
Incremental=yes

[Distribution]
Distribution=arch
Release=rolling
Mirror=http://arch.mirror.constant.com/
Repositories=core
			extra
			multilib

[Output]
ImageId=meownix
OutputDirectory=mkosi.output
Output=%i_%v_%a

