[Content]
Packages=
		dracut
		linux
		linux-firmware
		git
		gcc
		btrfs-progs
		e2fsprogs
		xfsprogs
		dosfstools
		skopeo
		dbus
		dbus-glib
		glib2
		shadow
		pacman
		ostree
		base
		polkit
		vim
		micro
		sudo
		just
		podman
		distrobox
		less
		man
		man-db
		man-pages
		mokutil
		zram-generator
		curl
		wget
		noto-fonts
		noto-fonts-extra
		noto-fonts-cjk
		noto-fonts-emoji
		unicode-emoji
		otf-font-awesome
		network-manager-applet
		inetutils
		net-tools
		bluez
		bluez-utils
		bluez-tools
		blueman
		usbutils
		zsh
		gtk3
		gtk4
		gtk-layer-shell
		gtk4-layer-shell
		gobject-introspection
		xdg-user-dirs
		diffutils
		cups
		cups-pdf
		cups-filters
		avahi
		nss-mdns
