[Content]
Packages=
		xwayland-satellite
		wlr-randr
		xdg-desktop-portal
		xorg-xwayland
		noctalia
		cava
		kimageformats
		tuned-ppd
		kitty
		gtkmm-4.0
		gtk4-layer-shell
		playerctl
		adwaita-cursors
		qt6-multimedia
		qt6ct
		nwg-look
		nautilus