[Content]
Packages=
		niri
		xwayland-satellite
		wlr-randr
		xdg-desktop-portal
		xdg-desktop-portal-gnome
		xdg-desktop-portal-gtk
		dms-shell-niri
		xorg-xwayland
		matugen
		cava
		kimageformats
		tuned-ppd
		kitty
		gtkmm-4.0
		gtk4-layer-shell
		playerctl
		brightnessctl
		adwaita-cursors
		qt6-multimedia