[Content]
Packages=
		niri
		xwayland-satellite
		wlr-randr
		xdg-desktop-portal
		xdg-desktop-portal-gnome
		xdg-desktop-portal-gtk
		xorg-xwayland
		noctalia
		cava
		kimageformats
		tuned-ppd
		kitty
		gtkmm-4.0
		gtk4-layer-shell
		playerctl
		adwaita-cursors
		qt6-multimedia
		qt6ct