[Content]
Packages=
		qemu-base
		qemu-ui-gtk
		qemu-ui-opengl
		qemu-audio-pipewire
		qemu-hw-display-virtio-gpu-pci
		qemu-hw-display-virtio-vga-gl
		qemu-hw-usb-host
		qemu-hw-usb-redirect
		edk2-ovmf
		swtpm